export const INIT_MOVIES = 'INIT_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const INIT_CHARACTERS = 'INIT_CHARACTERS';
export const SET_CHARACTERS = 'SET_CHARACTERS';

export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';

export const SET_LOADING_CHARACTERS = "SET_LOADING_CHARACTERS";
export const SET_LOADING_MOVIES = "SET_LOADING_MOVIES";

export const FETCH_FAILED = 'FETCH_FAILED';

export const CLEAN_ERROR = "CLEAN_ERROR";

export const SET_LOADING_MORE = "SET_LOADING_MORE";
