export const INIT_MOVIES = 'INIT_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const INIT_CHARACTERS = 'INIT_CHARACTERS';
export const SET_CHARACTERS = 'SET_CHARACTERS';

export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';

export const PREV_CHARACTERS = 'PREV_CHARACTERS';
export const PREV_MOVIES = 'PREV_MOVIES';